[[UNRESOLVED_IMPORT]]
id = "MISSING_CODEWARE"
file = "virtual-atelier-full/virtual-store/VirtualStoreController.reds"
line_contains = "Codeware"
message = "Virtual Atelier depends on Codeware but you don't have it installed."

[[UNRESOLVED_IMPORT]]
id = "MISSING_BROWSER_EXTENSION"
file = "virtual-atelier-full/SetupNewSite.reds"
line_contains = "BrowserExtension"
message = "You installed Virtual Atelier - Browser Extension addon but not Browser Extension itself."

[[UNRESOLVED_METHOD]]
id = "OUTDATED_GAME_VERSION"
file = "virtual-atelier-full/vendor-preview/FullscreenVendor.reds"
line_contains = "OnHandleGlobalRelease"
message = "Your game scripts or scripts cache is outdated, verify your game files integrity or update your game to version 2.1+"

[[UNRESOLVED_METHOD]]
id = "OUTDATED_GAME_VERSION"
file = "virtual-atelier/vendor-preview/FullscreenVendor.reds"
line_contains = "OnHandleGlobalRelease"
message = "Your game scripts or scripts cache is outdated, verify your game files integrity or update your game to version 2.1+"
