[[UNRESOLVED_TYPE]]
id = "MISSING_TWEAKXL"
file = "EnhancedCraft/EnhancedCraft-GenerateItems.reds"
line_contains  = "ScriptableTweak"
message = "Enhanced Craft depends on TweakXL but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\TweakXL\" folder."

[[UNRESOLVED_METHOD]]
id = "MISSING_TWEAKXL"
line_contains  = "TweakDBInterface"
message = "One of your mods depends on TweakXL but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\TweakXL\" folder."

[[UNRESOLVED_METHOD]]
id = "MISSING_TWEAKXL"
line_contains  = "TweakDBManager"
message = "One of your mods depends on TweakXL but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\TweakXL\" folder."

[[UNRESOLVED_REF]]
id = "MISSING_MOD_SETTINGS"
line_contains  = "ModSettings"
message = "One of your mods depends on Mod Settings but you don't have it installed. Try to (re)install it and make sure that you have \"red4ext\\plugins\\mod_settings\" folder."

[[UNRESOLVED_TYPE]]
id = "OUTDATED_TWEAKXL"
file = "EnhancedCraft/EnhancedCraft-GenerateItems.reds"
line_contains  = "TweakDBBatch"
message = "Enhanced Craft requires TweakXL version 1.4.2 or above."
